### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by lwqqc** [AndreaCodegoni/Tiny_model_4_CD#20]
Hello, in your paper, you mentioned that the model training was conducted on the NVIDIA GeForce RTX 2060 6GB GPU. However, when I attempted to run your source code on an NVIDIA GeForce RTX 4060Ti 8GB GPU, I encountered an "out of memory" issue. Even when I reduced the batch_size to 1, I still had to resort to mixed-precision training.
And in the scenario where batch_size is set to 1 and mixed-precision training is applied, the issue of non-convergence in the loss function has emerged.

**Comment by AndreaCodegoni** [comment]
Hello,

the out of memory issue is very unexpected. Do you have changed something in the model configuration or in the dataset? 
Are you using 256x256 images?
Can you please run the code in debugging and tell me the specific point where it goes out of memory?

The non convergence issue with batch_size=1 is due to the very noisy information that you are using to update the weights. If you want to train with batch_size=1 I think you have to switch to SGD as optimizer, tune the optimizer parameter and use more epochs. 
I have never experimented this, but I think that is better to find out why the out of memory issue occurs, fix that and then train with a bigger batch_size.

**Comment by lwqqc** [comment]
Thank you for your response. I have re-downloaded your source code and ran it on the LEVIR_CD dataset. However, I still encountered overflow issues. Here is the result of my debugging session：
![image](https://github.com/AndreaCodegoni/Tiny_model_4_CD/assets/144602241/1e70cc52-e680-466f-800c-7923fb3fde92)
```
Number of model parameters 285128

Epoch 0
Traceback (most recent call last):
  File "E:\Program Files\JetBrains\PyCharm Community Edition 2023.2.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1500, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "E:\Program Files\JetBrains\PyCharm Community Edition 2023.2.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\projects\Tiny_model_4_CD-main\training.py", line 267, in <module>
    run()
  File "D:\projects\Tiny_model_4_CD-main\training.py", line 250, in run
    train(
  File "D:\projects\Tiny_model_4_CD-main\training.py", line 180, in train
    training_phase(epc)
  File "D:\projects\Tiny_model_4_CD-main\training.py", line 113, in training_phase
    it_loss = evaluate(reference, testimg, mask)
  File "D:\projects\Tiny_model_4_CD-main\training.py", line 90, in evaluate
    generated_mask = model(reference, testimg).squeeze(1)
  File "E:\Users\Admin\anaconda3\envs\Tiny_CD\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Users\Admin\anaconda3\envs\Tiny_CD\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\projects\Tiny_model_4_CD-main\models\change_classifier.py", line 46, in forward
    features = self._encode(ref, test)
  File "D:\projects\Tiny_model_4_CD-main\models\change_classifier.py", line 53, in _encode
    ref, test = layer(ref), layer(test)
  File "E:\Users\Admin\anaconda3\envs\Tiny_CD\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Users\Admin\anaconda3\envs\Tiny_CD\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Users\Admin\anaconda3\envs\Tiny_CD\lib\site-packages\torch\nn\modules\container.py", line 215, in forward
    input = module(input)
  File "E:\Users\Admin\anaconda3\envs\Tiny_CD\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Users\Admin\anaconda3\envs\Tiny_CD\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Users\Admin\anaconda3\envs\Tiny_CD\lib\site-packages\torchvision\models\efficientnet.py", line 164, in forward
    result = self.block(input)
  File "E:\Users\Admin\anaconda3\envs\Tiny_CD\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Users\Admin\anaconda3\envs\Tiny_CD\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Users\Admin\anaconda3\envs\Tiny_CD\lib\site-packages\torch\nn\modules\container.py", line 215, in forward
    input = module(input)
  File "E:\Users\Admin\anaconda3\envs\Tiny_CD\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Users\Admin\anaconda3\envs\Tiny_CD\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Users\Admin\anaconda3\envs\Tiny_CD\lib\site-packages\torchvision\ops\misc.py", line 260, in forward
    return scale * input
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 384.00 MiB. GPU 0 has a total capacty of 8.00 GiB of which 771.00 MiB is free. Of the allocated memory 5.06 GiB is allocated by PyTorch, and 807.00 KiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
python-BaseException
```

**Comment by lwqqc** [comment]
Are you using 256x256 images?
I am using the original images from the LEVIR_CD dataset.

**Comment by AndreaCodegoni** [comment]
> Are you using 256x256 images? I am using the original images from the LEVIR_CD dataset.

This means that you are using images of dimension 1024x1024 instead of patches of 256x256.
This is also confirmed by your debugging where I see that the input of that layer has shape [8,48,512,512] and it is probably the second layer of the EfficientNet backbone.

If you want to run the code on a 8gb GPU you have to preprocess the original images in order to obtain patches or you can download the preprocessed patches following the link in the issue #19 (the links in the Readme seems to be outdated so try to download from the issue).

**Comment by lwqqc** [comment]
Thank you very much for your help and reminder, the problem has been solved.

**Comment by lwqqc** [comment]
Thank you very much for your help and reminder,the problem has been solved.



---- Replied Message ----
| From | Andrea ***@***.***> |
| Date | 12/28/2023 17:33 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [AndreaCodegoni/Tiny_model_4_CD] out of memory (Issue #20) |

Are you using 256x256 images? I am using the original images from the LEVIR_CD dataset.

This means that you are using images of dimension 1024x1024 instead of patches of 256x256.
This is also confirmed by your debugging where I see that the input of that layer has shape [8,48,512,512] and it is probably the second layer of the EfficientNet backbone.

If you want to run the code on a 8gb GPU you have to preprocess the original images in order to obtain patches or you can download the preprocessed patches following the link in the issue #19 (the links in the Readme seems to be outdated so try to download from the issue).
